### ISSUE TITLE
SQL Server Authentication

### ISSUE THREAD

**Issue by cernst33** [jbeloy/BTech_MaverickDistributing#1]
Trying to figure out why SQL Server is not authenticating our login properly. Have been talking to Network Solutions for the last couple days. Will resolve this when issue is completed.

**Comment by cernst33** [comment]
I got more info from Network Solutions, and they will be fixing the problem in the next 2-4 hours they said.

**Comment by jbeloy** [comment]
Sounds good thanks for the update!
